# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  build_all:
    desc: build backend and frontend
    deps: [build_frontend, build_backend]
    failfast: true

  build_frontend:
    desc: build frontend
    cmds:
      - 'echo "todo: frontend builder"'

  build_backend:
    desc: build backend
    dir: "./backend"
    cmds:
      - go build -o "../build/"

  build_run:
    desc: собирает всё и запускает
    aliases: [default]
    deps: [build_all]
    dir: build
    cmds:
      - ./ITI
