version: "2"
linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: the "Default" linters https://golangci-lint.run/docs/linters/#all-linters
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: all

  disable:
    - depguard
    - exhaustruct
    - wsl
    - ireturn
    - funcorder

  settings:
    wrapcheck:
      ignore-sigs:
        - github.com/labstack/echo/v5.(*Context).JSON
        - func (*github.com/labstack/echo/v5.Context).JSON(code int, i any) (err error)
        - fmt.Errorf
        - errors.New
        - func (github.com/gorilla/sessions.Store).Get(r *net/http.Request, name string) (*github.com/gorilla/sessions.Session, error)
    varnamelen:
      ignore-names:
        - c
        - db
    tagliatelle:
      case:
        rules:
          json: camel
          yaml: snake
          env: upperSnake
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
